Unit tests for visitors
nicdard/fusion-function-generator pull request #39
Opened 2022-05-04 23:52 UTC by nicdard

Add unit test for some visitors.

Following our zero dependency line, I have used [unittest](https://docs.python.org/3/library/unittest.html#module-unittest) which is shipped normally with python3 instead of pytest.

I also needed to implement `__eq__` and `__hash__` functions for the operators to actually compare two different tree of operators in the tests.

2022-05-09 23:40 UTC, lweitzendorf requested changes
Looks good for the most part, just two things:

1. Do you really want to keep the long, explicit imports for every single operator in the tests? It makes sense for the generated code, but I don't see the point here.
2. Maybe add at least one negative test that asserts the inequality of two different trees.

2022-05-10 11:08 UTC, nicdard commented
> Looks good for the most part, just two things:
> 
> 1. Do you really want to keep the long, explicit imports for every single operator in the tests? It makes sense for the generated code, but I don't see the point here.
> 2. Maybe add at least one negative test that asserts the inequality of two different trees.

1. Sorry this Is because I am used to import only what Is needed but I will change it
2. Oh I didn't think about it, thanks!

2022-05-10 21:31 UTC, nicdard commented
Should be fixed now :muscle:

2022-05-14 10:07 UTC, lweitzendorf approved these changes

2022-05-14 10:28 UTC, merged