feat: add z3str3 soundness issue
nicdard/fusion-function-generator pull request #69
Opened 2022-07-13 23:40 UTC by nicdard

2022-07-14 21:33 UTC, lweitzendorf requested changes

2022-07-14 21:33 UTC, lweitzendorf commented on bugs/README.md
> +| [QF_S_2](z3/qf_s-2.smt2)     | QF_S   | Soundness           | [#6159](https://github.com/Z3Prover/z3/issues/6159)                         | 14/07/22 |
For consistency, remove the last underscore in the first column

2022-07-14 21:47 UTC, lweitzendorf requested changes

2022-07-14 21:47 UTC, lweitzendorf commented on bugs/README.md
> +| [QF_S_2](z3/qf_s-2.smt2)     | QF_S   | Soundness           | [#6159](https://github.com/Z3Prover/z3/issues/6159)                         | 14/07/22 |
```suggestion
| [QF_S 2](z3/qf_s-2.smt2)     | QF_S   | Soundness           | [#6159](https://github.com/Z3Prover/z3/issues/6159)                         | 14/07/22 |
```

2022-07-15 20:25 UTC, nicdard commented on bugs/README.md
> +| [QF_S_2](z3/qf_s-2.smt2)     | QF_S   | Soundness           | [#6159](https://github.com/Z3Prover/z3/issues/6159)                         | 14/07/22 |
Sure I didn't notice!

2022-07-15 20:31 UTC, nicdard commented on bugs/README.md
> +| [QF_S_2](z3/qf_s-2.smt2)     | QF_S   | Soundness           | [#6159](https://github.com/Z3Prover/z3/issues/6159)                         | 14/07/22 |
Should be ok now

2022-07-15 20:42 UTC, merged