feat: add QF_BV assertion bug
nicdard/fusion-function-generator pull request #73
Opened 2022-07-24 19:42 UTC by nicdard

2022-07-24 23:55 UTC, lweitzendorf requested changes

2022-07-24 23:55 UTC, lweitzendorf commented on bugs/README.md
> +| [QF_BV_2](z3/qf_bv-2.smt2)   | QF_BV  | Assertion Violation | [#6180](https://github.com/Z3Prover/z3/issues/6180)                         | 21/07/22 |
```suggestion
| [QF_BV 2](z3/qf_bv-2.smt2)   | QF_BV  | Assertion Violation | [#6180](https://github.com/Z3Prover/z3/issues/6180)                         | 21/07/22 |
```

2022-07-29 18:14 UTC, nicdard commented on bugs/README.md
> +| [QF_BV_2](z3/qf_bv-2.smt2)   | QF_BV  | Assertion Violation | [#6180](https://github.com/Z3Prover/z3/issues/6180)                         | 21/07/22 |
done :)

2022-07-29 22:55 UTC, lweitzendorf approved these changes

2022-08-10 18:45 UTC, merged